server:
  port: 8080

spring:
  application:
    name: mrds-server
  datasource:
    url: "jdbc:mysql://localhost/rdsdb"
    username: "root"
    password: "root"
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 60